AWSTemplateFormatVersion: 2010-09-09
Description: |
  This template deploys EC2 isntances for Cloud One project
Parameters:
  Environment:
    Description: Environment
    Type: String
    AllowedValues:
      - DEV
      - TEST
      - STAGE
      - PROD
  VPC:
    Description: Select VPC ID for EC2 Instance
    Type: 'AWS::EC2::VPC::Id'
  Subnet:
    Description: Select SubnetId for EC2 Instance
    Type: 'AWS::EC2::Subnet::Id'
  AMI:
    Description: Select AMI ID for EC2 Instance
    Type: 'AWS::EC2::Image::Id'
    Default: /ami/latest/us-east-1/centos
    AllowedValues:
      - /ami/latest/us-east-1/centos
      - /ami/latest/us-east-1/centosdocker
  InstanceType:
    Description: Select the EC2 Instance Type
    Type: String
    AllowedValues:
      - t3.nano
      - t3.micro
      - t3.small
      - t3.medium
      - t3.large
      - t3.xlarge
      - t3.2xlarge
  SecurityGroup:
    Description: Select Security Group IDs for EC2 Instance
    Type: 'List<AWS::EC2::SecurityGroup::Id>'
  KeyPair:
    Description: Select Key Pair for EC2 Instance
    Type: 'AWS::EC2::KeyPair::KeyName'
  Name:
    Description: Name of the EC2 Instance; follows NCI naming convention nciws-p1234
    Type: String
    AllowedPattern: .+
    Default: nciws-xxxxx
  Function:
    Description: 'Specific business function of the larger project, not the project name'
    Type: String
  Created:
    Description: Creation Date MM-DD-YYYY
    Type: String
    Default: mm-dd-yyyy
  Creator:
    Description: Name of user launching this template
    Type: String
    Default: FirstName Lastname
  DOC:
    Description: 'Division, Office, or Center of the Business Owner for this system.'
    Type: String
    Default: IITOB
  FederalSystemOwner:
    Description: The first and last name of the Federal system owner.
    Type: String
    Default: Sue Pan
  OS:
    Description: Operating system of the EC2 instance.
    Type: String
    Default: 'CentOS 7.x'
    AllowedValues:
      - 'CentOS 7.x'
      - RHEL7
      - Window 2012
      - Window 2016
  IC:
    Description: The Institute that owns/sponsors this system.
    Type: String
    Default: NCI
  Project:
    Description: >-
      Project name that may span multiple systems; This may also be the business
      service provided by this system.
    Type: String
    Default: Project-Name
Metadata:
  'AWS::CloudFormation::Interface':
    ParameterGroups:
      - Label:
          default: General Configuration for EC2 Instance
        Parameters:
          - Environment
          - VPC
          - Subnet
          - AMI
          - InstanceType
          - SecurityGroup
          - KeyPair
      - Label:
          default: Required Tags for EC2 Instance
        Parameters:
          - Name
          - Function
          - Created
          - Creator
          - DOC
          - FederalSystemOwner
          - OS
          - IC
          - PatchGroup
          - Project
          
Resources:
  nihnetSG:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: !Join 
        - ' '
        - - Security Group to Identfy
          - !Ref Environment
          - !Ref Project
          - ' EC2 Instances'
      SecurityGroupIngress:
        - IpProtocol: -1
          FromPort: -1
          ToPort: -1
          CidrIp: 137.187.0.0/16
        - IpProtocol: -1
          FromPort: -1
          ToPort: -1
          CidrIp: 10.133.0.0/16
        - IpProtocol: -1
          FromPort: -1
          ToPort: -1
          CidrIp: 165.112.0.0/16
        - IpProtocol: -1
          FromPort: -1
          ToPort: -1
          CidrIp: 130.14.0.0/16
        - IpProtocol: -1
          FromPort: -1
          ToPort: -1
          CidrIp: 128.231.0.0/16
        - IpProtocol: -1
          FromPort: -1
          ToPort: -1
          CidrIp: 10.208.0.0/9
        - IpProtocol: -1
          FromPort: -1
          ToPort: -1
          CidrIp: 157.98.0.0/16
        - IpProtocol: -1
          FromPort: -1
          ToPort: -1
          CidrIp: 156.40.0.0/16
        - IpProtocol: -1
          FromPort: -1
          ToPort: -1
          CidrIp: 129.43.0.0/16
      VpcId: !Ref VPC
  ec2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: !Ref AMI
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyPair
      SecurityGroupIds: !Ref SecurityGroup
      SubnetId: !Ref Subnet
      IamInstanceProfile: ec2-role-ssm-cloudwatch-access
      UserData: !Base64 
        'Fn::Sub': >
          #!/bin/bash

          # set debug mode

          set -x


          #output log of ec2 userdata to /var/log/user-data.log

          exec > >(tee /var/log/user-data.log|logger -t user-data -s
          2>/dev/console) 2>&1

          # create and put some content in the file

          touch /home/centos/apphost_ec2_userdata.txt

          (

          cat << 'EOP'

          Hey there Cloud Team debug verification file!!!

          EOP

          ) > /home/centos/apphost_ec2_userdata.txt

          # install SSM Agent on Amazon EC2 instances
          cd /tmp
          sudo yum install -y https://s3.amazonaws.com/ec2-downloads-windows/SSMAgent/latest/linux_amd64/amazon-ssm-agent.rpm
          sudo systemctl enable amazon-ssm-agent
          sudo systemctl start amazon-ssm-agent
          sudo systemctl status amazon-ssm-agent

          hostnamectl set-hostname --static ${Name}.nci.nih.gov

          hostname

          sudo systemctl reboot
          
      Tags:
        - Key: Name
          Value: !Ref Name
        - Key: Function
          Value: !Ref Function
        - Key: backup
          Value: required
        - Key: Created
          Value: !Ref Created
        - Key: Creator
          Value: !Ref Creator
        - Key: DOC
          Value: !Ref DOC
        - Key: Environment Tier
          Value: !Ref Environment
        - Key: Federal System Owner
          Value: !Ref FederalSystemOwner
        - Key: OS
          Value: !Ref OS
        - Key: IC
          Value: !Ref IC
        - Key: Project
          Value: !Ref Project