apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: test-cluster
  region: us-east-1
  version: "1.18"

vpc:
  id: vpc-12334567890
  cidr: "192.168.0.0/16"     # (optional, must match CIDR used by the given VPC)
  securityGroup: sg-0a54e912336f103f0
  subnets:
    # must provide 'private' and/or 'public' subnets by availibility zone as shown
    private:
      us-east-1a:
        id: subnet-XXXXXXXXXXXXXXXXX
      us-east-1b:
        id: subnet-XXXXXXXXXXXXXXXXX
      us-east-1c:
        id: subnet-XXXXXXXXXXXXXXXXX
      us-east-1d:
        id: subnet-XXXXXXXXXXXXXXXXX
      us-east-1f:
        id: subnet-XXXXXXXXXXXXXXXXX
  clusterEndpoints:
    privateAccess: true
    publicAccess: true
privateCluster:
  enabled: false

iam:
  serviceRoleARN: arn:aws:iam::XXXXXXXX:role/AWSClusterServiceRoleForAmazonEKS
  fargatePodExecutionRoleARN: arn:aws:iam::XXXXXXXXXXXX:role/AWSFargatePodExecutionRole
  withOIDC: true

secretsEncryption:
    keyARN: arn:aws:kms:us-east-1:XXXXXXXXXXXXX:key/XXXXXXXXXXXXXXXXX

cloudWatch:
  clusterLogging:
    # enable specific types of cluster control plane logs
    enableTypes: ["api","audit", "authenticator", "controllerManager", "scheduler"]
    # all supported types: "api", "audit", "authenticator", "controllerManager", "scheduler"
    # supported special values: "*" and "all"
